### ISSUE TITLE
插件在Linux环境下Rejoin与Ping检测无限循环

### ISSUE THREAD

**Issue by Happies123** [CatMoe/MoeFilter#104]
核心：waterfall-1.20-559.jar
插件版本0.15
BC核心版本 1.20
客户端版本1.8.9
问题：在玩家进入第一个Ping检测后无限循环 后面调整配置为Rejoin后也是无限循环

**Comment by FallenCrystal** [comment]
请提供您的配置文件

**Comment by Happies123** [comment]
插件默认配置

**Comment by FallenCrystal** [comment]
有尝试刷新过服务器列表吗?
唯一可能发生Ping和加入检查乱序的原因是因为一直在被攻击或闲置状态下切换

**Comment by Happies123** [comment]
尝试过 服务器刚刚加载 无任何攻击

**Comment by FallenCrystal** [comment]
您需要在规定时间内完成检查. 如果玩家需要更久的时间完成检查 请调整[这里](https://github.com/CatMoe/MoeFilter/blob/stray/translation/src/main/kotlin/catmoe/fallencrystal/translation/utils/config/LoadConfig.kt#L498)

**Comment by FallenCrystal** [comment]
由于没有进一步提供关于问题的具体信息, 被标记为已经解决
如果您有其它问题或实际上没有解决问题, 请在[此处](https://github.com/CatMoe/MoeFilter/issues/new)打开一个新的issue

题外话: 已有重写该项目的计划 如果在通过虚拟服务器中的验证时出现任何问题(包括版本不支持) 首先尝试将反机器人模块模式从`HANDLE`改为`PACKET` 然后重启服务器 感谢理解
