### ISSUE TITLE
DosHacker Free压测方案可绕过

### ISSUE THREAD

**Issue by HackHsda** [CatMoe/MoeFilter#45]
使用MoeFiler DosHacker Free压测方案 虽然防住了 但是服务器直接崩溃 玩家无法进入
家宽 5900x 但是在压测的时候宽带是够的 压测了一段时间会卡 然后崩溃

**Comment by FallenCrystal** [comment]
无法100%保证拦截非Minecraft协议的连接和数据包

如果您要报告绕过 请提供测试的工具 (如果可以)并提供信息以讲述它是怎么绕过的

**Comment by FallenCrystal** [comment]
检查 https://github.com/CatMoe/MoeFilter/commit/7088676b4c1cbedfe147627dc66d0a4a94386700 的无效数据包缓解措施
