### ISSUE TITLE
未来会考虑兼容mc百科的传统motd格式么？

### ISSUE THREAD

**Issue by angushushu** [CatMoe/MoeFilter#74]
如题，现在的component格式mc百科不支持而且不到啥时候会支持。

**Comment by FallenCrystal** [comment]
我们不负责兼容非vanilla之外的客户端或机制支持.

> Edit: 这可能是由于缺少发送了某些数据包, 或确实不支持component导致的. 但在这种情况下, 无法保证任何**第三方**的ping解析器能够100%工作. 这不是我们的主要责任.
